const ANSWER_NOTES = [
  {
    id: "source",
    term: "소스 / Source",
    aliases: ["소스", "source", "Source", "원천 자료", "학습 소스"],
    category: "AI 기획",
    shortDefinition: "AI가 답변하거나 분석할 때 기준으로 삼는 원본 자료이다.",
    detail: "소스는 NotebookLM 같은 도구에 올리는 문서, 링크, 텍스트 자료를 뜻한다. AI가 이 자료를 바탕으로 요약, 질의응답, 기획서 초안을 만들기 때문에 출처가 분명한 자료를 넣는 것이 중요하다.",
    examPoint: "문제에서 'AI가 참조하는 자료', '업로드하는 기반 문서', '원천 지식 자료'가 나오면 소스 또는 Source가 정답이다.",
    commonPatterns: ["NotebookLM에 업로드하는 자료는?", "AI가 분석하는 기반 문서의 단위는?", "환각을 줄이기 위해 제공하는 원천 자료는?"],
    relatedTerms: ["NotebookLM", "Gemini", "데이터 자산화"]
  },
  {
    id: "notebooklm",
    term: "NotebookLM",
    aliases: ["NotebookLM", "노트북LM", "Notebook LM", "notebooklm"],
    category: "AI 기획",
    shortDefinition: "자료를 소스로 등록해 요약과 질의응답을 돕는 구글 AI 도구이다.",
    detail: "NotebookLM은 PDF, 문서, 웹 링크 등을 소스로 넣고 그 자료를 바탕으로 답변을 받는 AI 학습 도구이다. 웹 기획 단계에서는 자료 정리, 요구사항 분석, 기획서 초안 작성에 자주 활용된다.",
    examPoint: "문제에서 '구글 AI 기반 메모장', '소스를 등록해 분석', '출처 기반 답변'이 나오면 NotebookLM을 떠올린다.",
    commonPatterns: ["소스 문서를 분석하는 구글 도구는?", "자료 기반 질의응답을 가능하게 하는 도구는?", "웹 기획 단계에서 자료를 요약하는 도구는?"],
    relatedTerms: ["소스 / Source", "Gemini", "데이터 자산화"]
  },
  {
    id: "gemini",
    term: "Gemini",
    aliases: ["Gemini", "gemini", "제미나이"],
    category: "AI 기획",
    shortDefinition: "기획서 작성과 아이디어 정리에 활용되는 구글 생성형 AI이다.",
    detail: "Gemini는 텍스트 생성, 요약, 아이디어 확장에 쓰이는 생성형 AI이다. 웹 기획에서는 메뉴 구조, 화면 구성, 설명 문구, 요구사항 정리에 도움을 줄 수 있다.",
    examPoint: "문제에서 '구글 생성형 AI', '기획서 작성', '텍스트 분석'이 나오면 Gemini가 답일 수 있다.",
    commonPatterns: ["구글이 개발한 LLM은?", "기획서 작성에 활용하는 생성형 AI는?", "웹 기획 초안을 만드는 AI 모델은?"],
    relatedTerms: ["NotebookLM", "소스 / Source", "Prompt"]
  },
  {
    id: "data-assetization",
    term: "데이터 자산화",
    aliases: ["데이터 자산화", "자산화", "데이터베이스화"],
    category: "AI 기획",
    shortDefinition: "흩어진 자료를 AI가 활용하기 좋은 지식 자산으로 정리하는 과정이다.",
    detail: "데이터 자산화는 원시 자료를 모으고 정리해 기획, 분석, 재사용이 가능한 형태로 만드는 과정이다. 웹 기획에서는 자료를 소스로 정리하고 AI가 참고할 수 있게 구조화하는 의미로 자주 나온다.",
    examPoint: "문제에서 '자료를 가치 있는 자산으로 전환', '방대한 자료를 구조화'가 나오면 데이터 자산화가 정답이다.",
    commonPatterns: ["수집한 자료를 지식 자산으로 만드는 과정은?", "AI가 학습하기 좋게 자료를 구조화하는 것은?", "원시 데이터를 지속 가능한 가치로 바꾸는 과정은?"],
    relatedTerms: ["소스 / Source", "NotebookLM", "Gemini"]
  },
  {
    id: "prompt",
    term: "Prompt",
    aliases: ["프롬프트", "Prompt", "prompt", "지시문", "명령어"],
    category: "바이브 코딩",
    shortDefinition: "AI에게 원하는 작업을 지시하기 위해 입력하는 명령문이다.",
    detail: "프롬프트는 생성형 AI나 Antigravity 같은 AI 개발 도구에게 원하는 결과물, 기능, 디자인 방향, 수정 요청 등을 전달하는 입력문이다. 웹 개발에서는 버튼 색상 변경, 오류 수정, 레이아웃 생성 등 다양한 작업을 프롬프트로 지시할 수 있다.",
    examPoint: "문제에서 'AI에게 입력하는 명령어', '지시문', '요구사항을 전달하는 문장'이라는 표현이 나오면 Prompt 또는 프롬프트가 정답이다.",
    commonPatterns: ["AI에게 입력하는 명령어는?", "Antigravity에서 개발 의도를 전달하기 위해 사용하는 것은?", "생성형 AI에게 원하는 결과를 지시하는 문장은?"],
    relatedTerms: ["바이브 코딩", "Antigravity", "디버깅"]
  },
  {
    id: "vibe-coding",
    term: "바이브 코딩",
    aliases: ["바이브 코딩", "Vibe Coding", "vibe coding"],
    category: "바이브 코딩",
    shortDefinition: "코드를 직접 다 쓰기보다 AI와 대화하며 의도를 구현하는 개발 방식이다.",
    detail: "바이브 코딩은 세부 문법보다 설계 의도, 화면 구성, 기능 요구사항을 프롬프트로 전달하며 개발하는 방식이다. AI가 코드를 만들고 사람은 방향 제시와 검증을 맡는 흐름이 핵심이다.",
    examPoint: "문제에서 '코드 문법보다 설계 의도', 'AI와 대화하며 개발', '프롬프트 제어'가 나오면 바이브 코딩이다.",
    commonPatterns: ["AI와 대화하며 개발하는 방식은?", "문법보다 설계 의도 전달에 집중하는 코딩은?", "프롬프트로 코드를 제어하는 개발 방식은?"],
    relatedTerms: ["Prompt", "Antigravity", "디버깅"]
  },
  {
    id: "antigravity",
    term: "Antigravity",
    aliases: ["Antigravity", "antigravity", "앤티그래비티"],
    category: "바이브 코딩",
    shortDefinition: "프롬프트 기반으로 웹 개발을 진행하는 AI 개발 환경이다.",
    detail: "Antigravity는 사용자가 자연어로 요구사항을 입력하고 AI가 코드 작성과 수정을 돕는 개발 도구로 설명된다. 시험에서는 바이브 코딩, 프롬프트 제어, 디버깅과 함께 자주 등장한다.",
    examPoint: "문제에서 '앤티그래비티 기반 개발 환경'이 나오면 프롬프트, 바이브 코딩, 디버깅과 연결해 생각한다.",
    commonPatterns: ["Antigravity에서 입력하는 것은?", "앤티그래비티 기반 개발 방식은?", "AI에게 디자인 제어 방향을 전달하는 환경은?"],
    relatedTerms: ["Prompt", "바이브 코딩", "디버깅"]
  },
  {
    id: "debugging",
    term: "디버깅",
    aliases: ["디버깅", "Debugging", "debugging", "오류 수정"],
    category: "바이브 코딩",
    shortDefinition: "코드나 화면에서 발생한 오류를 찾아 고치는 과정이다.",
    detail: "디버깅은 버튼이 작동하지 않거나 레이아웃이 깨지는 등 문제의 원인을 찾아 수정하는 과정이다. 바이브 코딩에서는 에러 메시지와 현상을 프롬프트로 설명해 AI에게 수정을 요청하는 방식이 자주 나온다.",
    examPoint: "문제에서 '버그를 찾아 수정', '오류 해결', '에러 메시지를 AI에게 전달'이 나오면 디버깅이다.",
    commonPatterns: ["웹사이트 오류를 찾아 수정하는 과정은?", "에러 발생 시 AI에게 요청하는 과정은?", "레이아웃 깨짐을 고치는 작업은?"],
    relatedTerms: ["Prompt", "바이브 코딩", "Antigravity"]
  },
  {
    id: "hero-section",
    term: "히어로 섹션",
    aliases: ["히어로 섹션", "Hero Section", "hero section", "히어로"],
    category: "바이브 코딩",
    shortDefinition: "웹페이지 상단에서 핵심 메시지를 가장 먼저 보여주는 큰 영역이다.",
    detail: "히어로 섹션은 방문자가 처음 보는 상단 영역으로, 큰 제목, 대표 이미지, 핵심 문구, CTA 버튼 등이 들어간다. 서비스의 첫인상과 주목도를 높이는 역할을 한다.",
    examPoint: "문제에서 '웹 페이지 최상단', '대형 비주얼', '핵심 슬로건'이 나오면 히어로 섹션이다.",
    commonPatterns: ["사용자가 처음 보는 상단 주요 영역은?", "핵심 메시지를 보여주는 큰 배너 영역은?", "웹페이지 최상단 비주얼 영역은?"],
    relatedTerms: ["바이브 코딩", "반응형 디자인", "Prompt"]
  },
  {
    id: "github",
    term: "GitHub",
    aliases: ["GitHub", "Github", "github", "깃허브"],
    category: "배포 및 관리",
    shortDefinition: "소스 코드를 저장하고 버전 관리하는 온라인 플랫폼이다.",
    detail: "GitHub는 프로젝트 파일과 코드 기록을 저장하는 원격 저장소 서비스이다. 웹 프로젝트에서는 코드를 업로드하고 Vercel과 연동해 자동 배포하는 흐름으로 자주 나온다.",
    examPoint: "문제에서 '코드 저장', '버전 관리', '레포지토리 업로드'가 나오면 GitHub가 정답이다.",
    commonPatterns: ["소스 코드를 온라인에 저장하는 플랫폼은?", "버전 관리 호스팅 서비스는?", "Vercel과 연동하는 코드 저장소는?"],
    relatedTerms: ["Repository", "Vercel", "배포"]
  },
  {
    id: "repository",
    term: "Repository",
    aliases: ["Repository", "repository", "레포지토리", "저장소"],
    category: "배포 및 관리",
    shortDefinition: "프로젝트 코드와 파일이 저장되는 공간이다.",
    detail: "Repository는 GitHub에서 프로젝트 단위로 파일과 코드 변경 기록을 관리하는 저장소이다. 웹 배포 과정에서는 레포지토리에 코드를 올리고 Vercel이 이를 읽어 배포한다.",
    examPoint: "문제에서 '프로젝트 파일과 코드가 저장되는 저장소'가 나오면 Repository 또는 레포지토리이다.",
    commonPatterns: ["GitHub의 저장소를 무엇이라 하는가?", "프로젝트 코드가 저장되는 공간은?", "코드 버전 기록을 담는 곳은?"],
    relatedTerms: ["GitHub", "Vercel", "배포"]
  },
  {
    id: "vercel",
    term: "Vercel",
    aliases: ["Vercel", "vercel", "버셀", "버셸", "버샐"],
    category: "배포 및 관리",
    shortDefinition: "웹 프로젝트를 인터넷에 공개해 주는 클라우드 배포 플랫폼이다.",
    detail: "Vercel은 GitHub 저장소와 연결해 HTML, CSS, JavaScript로 만든 웹사이트를 자동 빌드하고 실시간으로 배포해 주는 서비스이다. 사용자는 배포 URL을 통해 사이트에 접속할 수 있다.",
    examPoint: "문제에서 '실시간 웹 배포', 'GitHub와 연동', '호스팅 URL 발급'이 나오면 Vercel이다.",
    commonPatterns: ["GitHub 코드를 실제 웹으로 배포하는 플랫폼은?", "실시간 호스팅을 제공하는 서비스는?", "웹사이트 URL을 발급해 주는 도구는?"],
    relatedTerms: ["GitHub", "Repository", "배포"]
  },
  {
    id: "deployment",
    term: "배포",
    aliases: ["배포", "Deployment", "deployment", "웹 배포"],
    category: "배포 및 관리",
    shortDefinition: "완성한 웹사이트를 사용자가 접속할 수 있도록 인터넷에 올리는 과정이다.",
    detail: "배포는 로컬에서 만든 파일을 외부 사용자가 볼 수 있게 서버나 호스팅 플랫폼에 올리는 단계이다. 수업 흐름에서는 GitHub에 코드를 저장하고 Vercel로 배포하는 방식이 자주 나온다.",
    examPoint: "문제에서 '인터넷에 올림', '사용자가 접속 가능하게 함', '온라인 공개'가 나오면 배포이다.",
    commonPatterns: ["웹사이트를 인터넷에 올리는 과정은?", "완성한 코드를 사용자에게 공개하는 단계는?", "Vercel을 이용해 수행하는 작업은?"],
    relatedTerms: ["GitHub", "Vercel", "index.html"]
  },
  {
    id: "url",
    term: "URL",
    aliases: ["URL", "url", "주소", "웹 주소"],
    category: "배포 및 관리",
    shortDefinition: "웹에서 특정 페이지나 자원의 위치를 나타내는 주소이다.",
    detail: "URL은 웹페이지, 이미지, 문서 같은 자원이 어디에 있는지 알려주는 주소 체계이다. 링크를 걸 때는 보통 a 태그의 href 속성에 URL을 넣는다.",
    examPoint: "문제에서 '웹상의 특정 페이지를 가리키는 주소', '목적지 주소'가 나오면 URL이다.",
    commonPatterns: ["웹 페이지의 고유 주소는?", "하이퍼링크의 목적지 주소는?", "웹 자원의 위치를 나타내는 것은?"],
    relatedTerms: ["<a>", "href", "DNS"]
  },
  {
    id: "dns",
    term: "DNS",
    aliases: ["DNS", "dns", "도메인 네임 시스템"],
    category: "배포 및 관리",
    shortDefinition: "도메인 이름을 실제 서버 주소로 연결해 주는 시스템이다.",
    detail: "DNS는 사람이 읽기 쉬운 도메인 이름을 컴퓨터가 찾을 수 있는 IP 주소와 연결한다. 배포된 사이트에 도메인을 붙일 때 필요한 기본 개념이다.",
    examPoint: "문제에서 '도메인 이름을 서버 주소로 변환'이 나오면 DNS이다.",
    commonPatterns: ["도메인과 IP를 연결하는 시스템은?", "웹 주소 이름을 서버 위치로 바꾸는 것은?", "도메인 설정에 필요한 개념은?"],
    relatedTerms: ["URL", "Vercel", "배포"]
  },
  {
    id: "index-html",
    term: "index.html",
    aliases: ["index.html", "index", "인덱스 파일"],
    category: "HTML",
    shortDefinition: "웹 서버가 폴더에서 가장 먼저 찾는 기본 시작 파일이다.",
    detail: "index.html은 사용자가 사이트에 접속했을 때 첫 화면으로 보여 주는 대표 HTML 파일이다. Vercel 같은 배포 환경에서도 루트 폴더의 시작점으로 자주 쓰인다.",
    examPoint: "문제에서 '홈페이지의 시작점', '가장 먼저 인식하는 파일', '대문 파일'이 나오면 index.html이다.",
    commonPatterns: ["웹 서버가 가장 먼저 찾는 파일은?", "홈페이지 시작점 파일 이름은?", "첫 화면으로 띄우는 기본 문서는?"],
    relatedTerms: ["배포", "Vercel", "<body>"]
  },
  {
    id: "head",
    term: "<head>",
    aliases: ["<head>", "head", "헤드"],
    category: "HTML",
    shortDefinition: "화면에는 직접 보이지 않는 문서 정보와 설정을 담는 영역이다.",
    detail: "head 태그에는 title, meta, link처럼 브라우저와 검색엔진이 참고하는 정보가 들어간다. 사용자가 보는 본문이 아니라 보이지 않는 두뇌 역할이라고 자주 설명된다.",
    examPoint: "문제에서 '보이지 않는 두뇌', '메타데이터', 'SEO와 CSS 연결'이 나오면 head이다.",
    commonPatterns: ["HTML의 보이지 않는 두뇌 영역은?", "문서 제목과 메타 정보를 담는 곳은?", "CSS 파일 연결 정보가 들어가는 영역은?"],
    relatedTerms: ["<title>", "<meta>", "<link>"]
  },
  {
    id: "body",
    term: "<body>",
    aliases: ["<body>", "body", "바디"],
    category: "HTML",
    shortDefinition: "웹페이지에서 사용자에게 실제로 보이는 내용이 들어가는 영역이다.",
    detail: "body 태그에는 텍스트, 이미지, 버튼, 링크처럼 화면에 표시되는 요소가 배치된다. head가 보이지 않는 설정이라면 body는 사용자가 직접 경험하는 화면이다.",
    examPoint: "문제에서 '화면에 보이는 내용', '사용자가 직접 경험하는 영역'이 나오면 body이다.",
    commonPatterns: ["HTML에서 화면에 보이는 부분은?", "텍스트와 이미지가 배치되는 영역은?", "사용자가 보는 UI 요소가 들어가는 태그는?"],
    relatedTerms: ["<head>", "index.html", "HTML"]
  },
  {
    id: "title",
    term: "<title>",
    aliases: ["<title>", "title", "타이틀"],
    category: "HTML",
    shortDefinition: "브라우저 탭에 표시되는 문서 제목을 정하는 태그이다.",
    detail: "title 태그는 head 내부에 작성하며 브라우저 탭 이름이나 검색 결과 제목으로 활용될 수 있다. 화면 본문 제목 h1과는 구분해야 한다.",
    examPoint: "문제에서 '브라우저 탭에 표시되는 공식 명칭'이 나오면 title이다.",
    commonPatterns: ["브라우저 탭 제목을 정하는 태그는?", "head 안에 들어가는 문서 제목 태그는?", "문서의 공식 명칭 태그는?"],
    relatedTerms: ["<head>", "<meta>", "<h1>"]
  },
  {
    id: "meta",
    term: "<meta>",
    aliases: ["<meta>", "meta", "메타 태그"],
    category: "HTML",
    shortDefinition: "문자 인코딩, 화면 크기 같은 문서 정보를 설정하는 태그이다.",
    detail: "meta 태그는 head 안에서 문서의 부가 정보를 브라우저와 검색엔진에 알려준다. UTF-8 문자 인코딩, viewport 설정처럼 화면이 깨지지 않게 하는 정보가 대표적이다.",
    examPoint: "문제에서 '문자 인코딩', 'viewport', '문서 메타데이터'가 나오면 meta 태그이다.",
    commonPatterns: ["UTF-8 설정에 쓰는 태그는?", "모바일 viewport 정보를 담는 태그는?", "문서 부가 정보를 설정하는 태그는?"],
    relatedTerms: ["<head>", "<title>", "<link>"]
  },
  {
    id: "link",
    term: "<link>",
    aliases: ["<link>", "link", "링크 태그"],
    category: "HTML",
    shortDefinition: "HTML 문서에 외부 CSS 같은 자원을 연결하는 태그이다.",
    detail: "link 태그는 보통 head 안에서 CSS 파일을 연결할 때 사용한다. 하이퍼링크를 만드는 a 태그와 헷갈리지 않는 것이 중요하다.",
    examPoint: "문제에서 'CSS 파일 연결', '외부 스타일시트 연결'이 나오면 link 태그이다.",
    commonPatterns: ["CSS 파일을 연결하는 태그는?", "외부 스타일시트를 불러오는 태그는?", "head 안에서 외부 자원을 연결하는 태그는?"],
    relatedTerms: ["<head>", "<meta>", "<a>"]
  },
  {
    id: "a",
    term: "<a>",
    aliases: ["<a>", "a", "a태그", "anchor", "앵커 태그"],
    category: "HTML",
    shortDefinition: "다른 페이지나 자원으로 이동하는 하이퍼링크를 만드는 태그이다.",
    detail: "a 태그는 href 속성에 이동할 URL을 넣어 링크를 만든다. 사용자가 클릭하면 다른 문서, 페이지, 사이트로 이동할 수 있다.",
    examPoint: "문제에서 '하이퍼링크 생성', '다른 문서로 이동'이 나오면 a 태그이다.",
    commonPatterns: ["하이퍼링크를 만드는 태그는?", "다른 페이지로 이동시키는 태그는?", "href와 함께 쓰는 태그는?"],
    relatedTerms: ["href", "URL", "<link>"]
  },
  {
    id: "href",
    term: "href",
    aliases: ["href", "href 속성"],
    category: "HTML",
    shortDefinition: "a 태그에서 이동할 목적지 주소를 지정하는 속성이다.",
    detail: "href는 링크의 목적지 URL을 넣는 속성이다. a 태그 안에 href를 작성해야 클릭했을 때 어디로 이동할지 정할 수 있다.",
    examPoint: "문제에서 'a 태그의 목적지 주소 속성'이 나오면 href이다.",
    commonPatterns: ["하이퍼링크 목적지 주소 속성은?", "<a> 태그에서 URL을 지정하는 속성은?", "link.com 같은 값을 담는 속성명은?"],
    relatedTerms: ["<a>", "URL", "src"]
  },
  {
    id: "img",
    term: "<img>",
    aliases: ["<img>", "img", "이미지 태그"],
    category: "HTML",
    shortDefinition: "웹페이지에 이미지를 삽입하는 태그이다.",
    detail: "img 태그는 이미지를 화면에 보여 주는 태그이며 src로 이미지 경로를 지정하고 alt로 대체 텍스트를 제공한다. 일반적으로 닫는 태그 없이 쓰는 self-closing 형태이다.",
    examPoint: "문제에서 '이미지 삽입', 'src와 alt를 사용하는 태그'가 나오면 img 태그이다.",
    commonPatterns: ["이미지를 삽입하는 태그는?", "src와 alt를 함께 쓰는 태그는?", "닫는 태그가 없는 이미지 태그는?"],
    relatedTerms: ["src", "alt", "Self-closing tag"]
  },
  {
    id: "src",
    term: "src",
    aliases: ["src", "src 속성"],
    category: "HTML",
    shortDefinition: "이미지나 미디어 파일의 경로를 지정하는 속성이다.",
    detail: "src는 source의 줄임말로, img 태그에서 불러올 이미지 파일의 위치를 지정한다. 링크 목적지인 href와 구분해야 한다.",
    examPoint: "문제에서 '이미지 경로를 지정하는 속성'이 나오면 src이다.",
    commonPatterns: ["이미지 파일 경로 속성은?", "<img>에서 image.jpg를 넣는 속성은?", "미디어 원본 위치를 지정하는 속성은?"],
    relatedTerms: ["<img>", "alt", "href"]
  },
  {
    id: "alt",
    term: "alt",
    aliases: ["alt", "alt 속성", "대체 텍스트"],
    category: "HTML",
    shortDefinition: "이미지를 설명하는 대체 텍스트 속성이다.",
    detail: "alt는 이미지가 보이지 않을 때 대신 보여 주거나 스크린 리더가 읽을 수 있는 설명이다. 접근성과 SEO 측면에서 중요한 속성이다.",
    examPoint: "문제에서 '이미지를 불러오지 못할 때 대신 보여줄 텍스트', '대체 텍스트'가 나오면 alt이다.",
    commonPatterns: ["이미지 대체 텍스트 속성은?", "이미지를 설명하는 속성은?", "스크린 리더가 읽는 이미지 설명은?"],
    relatedTerms: ["<img>", "src", "시맨틱 태그 / 의미론적 태그"]
  },
  {
    id: "block-element",
    term: "블록 요소",
    aliases: ["블록 요소", "Block-level", "Block-level element", "block", "블록"],
    category: "HTML",
    shortDefinition: "가로 폭을 크게 차지하고 새 줄에서 시작하는 HTML 요소이다.",
    detail: "블록 요소는 보통 브라우저 가로 폭 전체를 차지하고 앞뒤로 줄바꿈이 생긴다. div, p, h1 같은 태그가 대표 예시이다.",
    examPoint: "문제에서 '가로 폭 100%', '항상 새로운 줄', '수직으로 쌓임'이 나오면 블록 요소이다.",
    commonPatterns: ["가로 폭 100%를 차지하는 요소는?", "자동 줄바꿈이 되는 요소는?", "div, p, h1은 어떤 요소인가?"],
    relatedTerms: ["인라인 요소", "<body>", "마트료시카 상자 모델"]
  },
  {
    id: "inline-element",
    term: "인라인 요소",
    aliases: ["인라인 요소", "Inline-level", "Inline-level element", "inline", "인라인"],
    category: "HTML",
    shortDefinition: "콘텐츠 크기만큼만 차지하고 옆으로 나란히 배치되는 요소이다.",
    detail: "인라인 요소는 줄 전체를 차지하지 않고 텍스트 흐름 안에서 필요한 만큼만 공간을 쓴다. span, a, strong 등이 대표적인 예시이다.",
    examPoint: "문제에서 '콘텐츠 크기만큼만 차지', '줄바꿈 없이 나란히 배치'가 나오면 인라인 요소이다.",
    commonPatterns: ["줄바꿈 없이 나란히 배치되는 요소는?", "span, a, strong은 어떤 요소인가?", "콘텐츠 크기만큼만 공간을 차지하는 요소는?"],
    relatedTerms: ["블록 요소", "<span>", "<a>"]
  },
  {
    id: "semantic-tag",
    term: "시맨틱 태그 / 의미론적 태그",
    aliases: ["시맨틱 태그", "의미론적 태그", "Semantic Tag", "Semantic HTML", "시맨틱", "의미론적 구조"],
    category: "HTML",
    shortDefinition: "요소의 역할과 의미가 드러나도록 사용하는 HTML 태그이다.",
    detail: "시맨틱 태그는 header, nav, main, footer처럼 영역의 의미를 브라우저, 검색엔진, 스크린 리더가 이해하기 쉽게 해 준다. 단순히 공간만 나누는 div와 구분된다.",
    examPoint: "문제에서 'SEO', '스크린 리더', '요소의 역할을 명확히'가 나오면 시맨틱 태그이다.",
    commonPatterns: ["div 대신 역할을 명확히 하는 태그는?", "검색엔진이 구조를 이해하게 돕는 태그는?", "header, nav, main 같은 태그는?"],
    relatedTerms: ["<head>", "alt", "HTML"]
  },
  {
    id: "matryoshka",
    term: "마트료시카 상자 모델",
    aliases: ["마트료시카", "마트료시카 상자 모델", "포함과 중첩 법칙", "중첩 구조"],
    category: "HTML",
    shortDefinition: "부모 요소가 자식 요소를 올바르게 감싸는 HTML 중첩 구조를 비유한 말이다.",
    detail: "HTML 요소는 여는 태그와 닫는 태그의 경계가 맞아야 하며, 부모 요소 안에 자식 요소가 완전히 들어가야 한다. 상자 안에 상자를 넣는 구조처럼 생각하면 된다.",
    examPoint: "문제에서 '부모가 자식을 감싼다', '상자 안의 상자', '중첩 오류'가 나오면 마트료시카 상자 모델이다.",
    commonPatterns: ["HTML의 포함과 중첩 구조 비유는?", "부모 요소가 자식 요소를 감싸는 모델은?", "태그 중첩 오류와 관련된 개념은?"],
    relatedTerms: ["블록 요소", "Self-closing tag", "HTML"]
  },
  {
    id: "self-closing",
    term: "Self-closing tag",
    aliases: ["Self-closing tag", "self-closing", "셀프 클로징 태그", "닫는 태그가 없는 태그"],
    category: "HTML",
    shortDefinition: "닫는 태그 없이 스스로 경계를 닫는 형태의 태그이다.",
    detail: "Self-closing tag는 별도의 닫는 태그를 작성하지 않는 태그를 뜻한다. img 태그처럼 콘텐츠를 감싸기보다 속성으로 정보를 넣는 태그에서 자주 설명된다.",
    examPoint: "문제에서 '닫는 태그가 없다', '스스로 경계를 닫는다', 'img 태그의 형태'가 나오면 Self-closing tag이다.",
    commonPatterns: ["닫는 태그가 없는 태그 형태는?", "img 태그의 특성은?", "스스로 닫히는 태그를 영어로?"],
    relatedTerms: ["<img>", "src", "alt"]
  },
  {
    id: "physical-ai",
    term: "피지컬 AI",
    aliases: ["피지컬 AI", "피지컬AI", "Physical AI", "physical ai", "체화된 지능"],
    category: "피지컬 AI",
    shortDefinition: "현실 세계에서 물리 법칙을 겪으며 행동하는 인공지능이다.",
    detail: "피지컬 AI는 텍스트나 이미지만 만드는 AI와 달리 로봇, 자율주행, 스마트 공간처럼 실제 물리 세계에서 판단하고 움직이는 AI를 뜻한다. 실패하면 기계 파손이나 안전 문제가 생길 수 있어 정확성이 중요하다.",
    examPoint: "문제에서 '3차원 현실 세계', '물리적 제어', '행동 중심 AI'가 나오면 피지컬 AI이다.",
    commonPatterns: ["현실 세계에서 행동하는 AI는?", "로봇과 물리 법칙을 다루는 AI는?", "생성형 AI와 달리 행동을 수행하는 지능은?"],
    relatedTerms: ["Sim2Real 격차", "WFM", "RFM"]
  },
  {
    id: "sim2real",
    term: "Sim2Real 격차",
    aliases: ["Sim2Real", "Sim2Real 격차", "sim2real", "심투리얼", "가상-현실 격차"],
    category: "피지컬 AI",
    shortDefinition: "가상 시뮬레이션과 현실 환경 사이의 차이 때문에 생기는 오차이다.",
    detail: "Sim2Real 격차는 가상 세계에서 잘 학습한 로봇이 현실의 마찰, 바람, 바닥 질감 같은 변수를 만나 제대로 작동하지 못하는 문제를 말한다.",
    examPoint: "문제에서 '가상에서 현실로 넘어올 때', '현실 변수 때문에 오작동', '시뮬레이션과 현실의 간극'이 나오면 Sim2Real 격차이다.",
    commonPatterns: ["가상 학습이 현실에 적용될 때 생기는 간극은?", "로봇이 현실 변수 때문에 넘어지는 현상은?", "Sim과 Real 사이의 차이는?"],
    relatedTerms: ["피지컬 AI", "PINN", "SDG"]
  },
  {
    id: "wfm",
    term: "WFM / 월드 파운데이션 모델",
    aliases: ["WFM", "wfm", "월드 파운데이션 모델", "World Foundation Model"],
    category: "피지컬 AI",
    shortDefinition: "세상의 물리 법칙을 학습해 미래를 예측하는 로봇의 두뇌 모델이다.",
    detail: "WFM은 중력, 충돌, 마찰 같은 물리 법칙을 이해하고 다음에 어떤 일이 일어날지 예측하는 모델로 설명된다. 피지컬 AI에서 세상을 이해하는 두뇌 역할을 한다.",
    examPoint: "문제에서 '로봇의 두뇌', '세상의 법칙 학습', '미래 예측'이 나오면 WFM이다.",
    commonPatterns: ["물리 법칙을 학습하는 로봇의 두뇌는?", "미래를 예측하는 파운데이션 모델은?", "World Foundation Model의 약자는?"],
    relatedTerms: ["피지컬 AI", "RFM", "PINN"]
  },
  {
    id: "rfm",
    term: "RFM / 로보틱스 파운데이션 모델",
    aliases: ["RFM", "rfm", "로보틱스 파운데이션 모델", "Robotics Foundation Model"],
    category: "피지컬 AI",
    shortDefinition: "시각과 언어를 이해해 로봇 행동 제어 명령으로 바꾸는 모델이다.",
    detail: "RFM은 로봇의 신경과 근육처럼 인식한 정보를 실제 관절, 모터, 행동 명령으로 연결하는 모델이다. '생각을 행동으로 바꾸는 모델'로 기억하면 쉽다.",
    examPoint: "문제에서 '로봇의 신경과 근육', '관절과 모터 제어', '행동 명령'이 나오면 RFM이다.",
    commonPatterns: ["로봇 행동 제어 모델은?", "시각과 언어를 물리 제어 명령으로 바꾸는 모델은?", "Robotics Foundation Model의 약자는?"],
    relatedTerms: ["WFM", "피지컬 AI", "인지 → 판단 → 행동"]
  },
  {
    id: "pinn",
    term: "PINN / 물리 정보 신경망",
    aliases: ["PINN", "pinn", "물리 정보 신경망", "Physics-Informed Neural Network"],
    category: "피지컬 AI",
    shortDefinition: "AI에 물리 방정식을 반영해 학습시키는 신경망 기술이다.",
    detail: "PINN은 뉴턴의 운동 법칙 같은 물리 방정식을 AI 학습에 넣어 현실 법칙을 어기지 않도록 돕는 기술이다. 부족한 현실 데이터를 보완하고 Sim2Real 문제를 줄이는 방법으로 나온다.",
    examPoint: "문제에서 '물리 방정식을 직접 입력', '뉴턴 운동 법칙', '물리 법칙을 강제'가 나오면 PINN이다.",
    commonPatterns: ["물리 방정식을 AI 뇌 구조에 넣는 기술은?", "뉴턴 법칙을 학습에 반영하는 신경망은?", "Sim2Real 극복을 위한 물리 정보 신경망은?"],
    relatedTerms: ["Sim2Real 격차", "SDG", "WFM"]
  },
  {
    id: "sdg",
    term: "SDG / 합성 데이터",
    aliases: ["SDG", "sdg", "합성 데이터", "합성 데이터 생성", "Synthetic Data Generation"],
    category: "피지컬 AI",
    shortDefinition: "현실에서 얻기 어려운 데이터를 가상으로 만들어 학습에 쓰는 기술이다.",
    detail: "SDG는 위험하거나 드문 상황을 가상 시뮬레이션에서 반복해 가짜 경험 데이터로 만드는 기술이다. 피지컬 AI의 데이터 부족 문제를 해결하는 핵심 방법으로 나온다.",
    examPoint: "문제에서 '가상에서 수백만 번 반복', '가짜 경험 데이터', '희귀 상황 데이터 생성'이 나오면 SDG 또는 합성 데이터이다.",
    commonPatterns: ["부족한 현실 데이터를 보완하는 기술은?", "가상에서 가짜 경험을 만드는 것은?", "Synthetic Data Generation의 약자는?"],
    relatedTerms: ["PINN", "Sim2Real 격차", "피지컬 AI"]
  },
  {
    id: "on-device-ai",
    term: "온디바이스 AI",
    aliases: ["온디바이스 AI", "온디바이스AI", "On-device AI", "on-device ai"],
    category: "피지컬 AI",
    shortDefinition: "기기 내부에서 직접 연산해 스스로 판단하는 AI 방식이다.",
    detail: "온디바이스 AI는 인터넷이나 외부 서버에 의존하지 않고 기기 자체에서 AI 연산을 수행한다. 로봇이나 엣지 환경에서는 빠른 반응과 안정성이 중요하기 때문에 자주 언급된다.",
    examPoint: "문제에서 '인터넷 없이 스스로', '기기 내부 연산', '엣지 환경'이 나오면 온디바이스 AI이다.",
    commonPatterns: ["로봇이 기기 안에서 직접 판단하는 AI는?", "외부 서버 없이 동작하는 AI는?", "엣지 환경에서 즉시 연산하는 방식은?"],
    relatedTerms: ["양자화", "피지컬 AI", "RFM"]
  },
  {
    id: "quantization",
    term: "양자화",
    aliases: ["양자화", "Quantization", "quantization"],
    category: "피지컬 AI",
    shortDefinition: "AI 모델을 작게 줄여 빠르고 가볍게 실행하도록 만드는 과정이다.",
    detail: "양자화는 큰 AI 모델의 지능은 최대한 유지하면서 계산 크기와 메모리 사용량을 줄이는 압축 방식이다. 로봇이나 엣지 기기에서 빠르게 실행하기 위해 필요하다.",
    examPoint: "문제에서 '모델 크기를 줄임', '엣지 환경에서 즉각 연산', 'AI 모델 압축'이 나오면 양자화이다.",
    commonPatterns: ["AI 모델의 크기를 줄이는 과정은?", "엣지 기기에서 빠르게 실행하기 위한 압축은?", "모델을 가볍게 만드는 기술은?"],
    relatedTerms: ["온디바이스 AI", "피지컬 AI", "RFM"]
  },
  {
    id: "perception-decision-action",
    term: "인지 → 판단 → 행동",
    aliases: ["인지 → 판단 → 행동", "인지 판단 행동", "인지-판단-행동", "Perception Decision Action"],
    category: "피지컬 AI",
    shortDefinition: "환경을 보고 이해한 뒤 결정하고 실제 행동으로 옮기는 AI 흐름이다.",
    detail: "피지컬 AI는 먼저 주변을 인지하고, 목표와 상황에 맞게 판단한 다음, 로봇이나 장치를 통해 행동한다. 단순 정보 생성이 아니라 실제 행동까지 이어지는 점이 핵심이다.",
    examPoint: "문제에서 '보고 생각하고 움직임', '행동 중심 제어 흐름'이 나오면 인지 → 판단 → 행동 구조를 떠올린다.",
    commonPatterns: ["피지컬 AI의 행동 흐름은?", "환경을 보고 결정한 뒤 움직이는 과정은?", "로봇 AI가 현실에서 작동하는 단계는?"],
    relatedTerms: ["피지컬 AI", "RFM", "WFM"]
  }
];
